CREATE VIEW CUSTOMER_CREDIT_CONTROL AS 
SELECT SALES_ID,CUSTOMER_NAME,MON,YR,
SALESPRICE_PER_UNIT-CREDITPAY_REPAYMENT AS DUE_AMOUT
FROM SALES
WHERE SALESPRICE_PER_UNIT-CREDITPAY_REPAYMENT IS NOT NULL AND SALESPRICE_PER_UNIT-CREDITPAY_REPAYMENT >0
ORDER BY MON DESC
WITH READ ONLY;