CREATE VIEW CUSTOMERS AS 
SELECT SALES_ID,CUSTOMER_NAME,BRAND,CATEGORIES,ITEM_SIZE,COLOR,
SALESPRICE_PER_UNIT-PURCHASEPRICE_PER_UNIT AS GROSS_PROFIT
FROM SALES
ORDER BY CUSTOMER_NAME
WITH READ ONLY;