CREATE VIEW PURCHASE_CREDIT_CONTROL AS 
SELECT ITEM_NUMBER,BRAND,CREDIT_BUY_LIMITDAYS,MON,YR,
PURCHASEPRICE_PER_UNIT-CREDITBUY_REPAYMENT AS OWING_AMOUT
FROM PURCHASE
WHERE PURCHASEPRICE_PER_UNIT-CREDITBUY_REPAYMENT IS NOT NULL AND PURCHASEPRICE_PER_UNIT-CREDITBUY_REPAYMENT >0
ORDER BY MON DESC
WITH READ ONLY;