SELECT * FROM PURCHASE

ALTER TABLE PURCHASE ADD PURCHASE_ID NUMBER;

CREATE SEQUENCE PURCHASE_ID
MINVALUE 1
MAXVALUE 999999999
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER PURCHASE_INSERT_T1 
BEFORE INSERT ON PURCHASE FOR EACH ROW 
DECLARE
BEGIN
    SELECT PURCHASE_ID.nextval INTO :NEW.PURCHASE_ID
    FROM DUAL;
END;

INSERT INTO PURCHASE(
ITEM_NUMBER,
PURCHASEPRICE_PER_UNIT,
CATEGORIES,
ITEM_SIZE,
COLOR,
WHETHER_CREDIT_BUY,
CREDIT_BUY_LIMITDAYS,
CREDITBUY_REPAYMENT,
MON,
YR,
SUPPLIER_ID)
VALUES(556,31,'SCARF','NORMAL','PINK','YES',60,0,'DEC','2021',1);

UPDATE PURCHASE
SET PURCHASE.BRAND =(
SELECT BRAND 
FROM SUPPLIERS
WHERE SUPPLIERS.SUPPLIER_ID = PURCHASE.SUPPLIER_ID);

CREATE OR REPLACE TRIGGER PUR_INVEN_UPDATE_T2 
AFTER INSERT ON PURCHASE FOR EACH ROW 
BEGIN
    INSERT INTO INVENTORY_IN_STORE(BRAND,CATEGORIES,ITEM_SIZE,COLOR,PURCHASEPRICE_PER_UNIT,ITEM_NUMBER,MON,YR) 
    VALUES(:NEW.BRAND,:NEW.CATEGORIES,
    :NEW.ITEM_SIZE,:NEW.COLOR, :NEW.PURCHASEPRICE_PER_UNIT, 
    :NEW.ITEM_NUMBER,:NEW.MON,:NEW.YR);
END;

SELECT * FROM INVENTORY_IN_STORE;

SELECT COUNT(*) FROM PURCHASE;
SELECT COUNT(*) FROM INVENTORY_IN_STORE;