CREATE SEQUENCE S_ID
MINVALUE 1
MAXVALUE 999999999
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER SALES_INSERT_T1 
BEFORE INSERT ON SALES FOR EACH ROW 
DECLARE
BEGIN
    SELECT S_ID.nextval INTO :NEW.SALES_ID
    FROM DUAL;
END;

---1
SELECT * FROM INVENTORY_IN_STORE WHERE ITEM_NUMBER = 18;
---2
INSERT INTO SALES (INVENTORY_ID,BRAND,CATEGORIES,ITEM_SIZE,COLOR,PURCHASEPRICE_PER_UNIT)
SELECT INVENTORY_ID,BRAND,CATEGORIES,ITEM_SIZE,COLOR,PURCHASEPRICE_PER_UNIT
FROM INVENTORY_IN_STORE
WHERE INVENTORY_ID = 154;
---3
DELETE INVENTORY_IN_STORE WHERE INVENTORY_ID = 154;
---4
SELECT * FROM SALES WHERE INVENTORY_ID = 154;
---5
UPDATE SALES 
SET
SALESPRICE_PER_UNIT=50,
CUSTOMER_NAME='DOG AUNT',
WHETHER_CREDIT_PAY='NO',
CREDITPAY_REPAYMENT=NULL,
MON='MAY',
YR='2021'
WHERE INVENTORY_ID = 154;
---6
SELECT * FROM SALES WHERE INVENTORY_ID = 154;